### ISSUE TITLE
wrong data if page is not "virtualTerminal"

### ISSUE THREAD

**Issue by danyo82** [saedyousef/askdante-extension#2]
The calculated worktime is only displayed correctly on the page https://my.askdante.com/virtualTerminal. On other AskDante-pages like https://my.askdante.com/attendance the worktime-overlay-window will show wrong data.

![image](https://github.com/saedyousef/askdante-extension/assets/19715087/d9e2657b-b711-4951-b277-37faed203253)

One option to circumvent this, could be to be more restrictive in  `content_scripts.matches` in `manifest.json` to only match the page `https://my.askdante.com/virtualTerminal`

**Comment by saedyousef** [comment]
Issue has been resolved by this commit https://github.com/saedyousef/askdante-extension/commit/e84485d248f5698c5003e8a16e4668faf308548c
